# Generated by Django 6.0.5 on 2026-06-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
