# Generated by Django 6.0.5 on 2026-06-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follows',
            new_name='followers',
        ),
    ]
